[package]
name = "ai_embedded_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"

[dependencies.uuid]
version = "1.3.3"
features = [
    "v4"
]